# this file represents how the gazebo_ros2_control plugin should instantiate its *own* ros2_control controller_manager
# this file is *not* used in the tradional way of Node + Param array
my_rotate_bot_controller:
  ros__parameters:
    type: joint_trajectory_controller/JointTrajectoryController
    joints:
       - link_1_JOINT_0
    write_op_modes:
       - link_1_JOINT_0
    state_publish_rate: 25
    action_monitor_rate: 20
    constraints:
      stopped_velocity_tolerance: 0.05
      goal_time: 5

joint_state_controller:
  ros__parameters:
    type: joint_state_controller/JointStateController
    publish_rate: 50